version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      JWT_ACCESS_SECRET: "Mykey"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  auth-service:
    build: ./auth-service
    container_name: auth-service
    command: npm run start:dev
    ports:
      - "3001:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: auth_db
      JWT_ACCESS_SECRET: "Mykey"
      JWT_ACCESS_EXPIRES: "15m"
      JWT_REFRESH_EXPIRES: "7d"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth-db:
        condition: service_healthy

  order-worker:
    build: ./order-worker
    container_name: order-worker
    command: npm run start:dev
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      # Added missing DB config so it connects to 'postgres' container instead of localhost
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-worker
    ports:
      - "3002:3000"
    volumes:
      - ./order-worker:/app
      - /app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-worker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  auth_pgdata: