
export const NOTIFICATION_OPTIONS = 'NOTIFICATION_OPTIONS';
export const NOTIFICATION_FEATURES = 'NOTIFICATION_FEATURES';


export const NOTIFICATION_FEATURE_OPTIONS = 'NOTIFICATION_FEATURES';
export const NOTIFICATION_FEATURE_REGISTRY = 'NOTIFICATION_FEATURES';


export const NOTIFY_METADATA = 'NOTIFY_METADATA';